### PR TITLE
Development

### PR DESCRIPTION
**Pull request by daashandayo**

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @daashandayo and @bellom ,

Good job. Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## General

- [x] The project has a descriptive README.md

## Features

### Authentication

- [x] The application uses the `bcrypt` gem for authentication ( You can use `User.authenticate(password)` )

### `Sessions`

- [x] The remember token is stored in a cookie
- [ ] The application remembers the user with the stored remember token. Please check issue #11 
- [x] You can `sign_out` of the application

### `Posts`

#### `:new`

- [x] The application can create posts (`:new`)
- [x] If a post is created successfully the application redirects to the post  `index` view

#### `:index`

- [x] The application can list all posts (`:index`)
- [x] A post's author is displayed only if you are signed in

## Models

### `User`

- [x] It has a `remember_token` field
- [x] A remember token is generated and encrypted with a `before_create` callback
- [ ] User data validations need for creating a new user. Every field data should be presence

## Controllers

### Application

- [x] It has a `current_user` method that uses the `||=` operator

### Posts

- [x] It uses `before_action` to restrict access to the `:new` and `:create` methods"

- [x] The `new` action uses the `current_user` method to build a post. E.g.

  ```ruby
  def new
    @post = current_user.post.build
  end
  ```

After fixing the unchecked issue please send another request to re-review this project. If you need any clarification based on this feedback then leave a comment by tagging me.

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @daashandayo and @bellom ,

 So far so good. Except for issue #13 . All is okay. for this issue, I am unable to check to remember me feature. I also applied all the steps you told me to do via slack. Can you please recheck and confirm that there is no issue?

Thanks 🙏

**Comment by bellom** [comment]
Will are going to confirm that now and get back to you.
Thanks

**Comment by dipto0321** [comment]
HI @bellom and @daashandayo ,

I checked it. Now it's okay. I liked that this project has a good UI. This is from me 👍 . You can merge it into the master.

Thanks 😌

**Pull request merged**
